FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

# [eslint] EACCES: permission denied, mkdir '/usr/src/app/node_modules/.cache'
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY ./ ./

CMD ["npm", "run", "start"]